### ISSUE TITLE
ETA on Dense FlashAttention ?

### ISSUE THREAD

**Issue by brappier** [philipturner/metal-flash-attention#1]
Holy shit, this project is amazing. 
Dense flash attention will be ultra useful, in running language models and stable diffusion. Whats the ETA and challenges you are facing? Maybe I can help. 

Also, maybe do you want to extend this project in making a high level framework like Triton for Metal? 

Also, folks from Apple are looking at your project closely!! Amazing work!

**Comment by philipturner** [comment]
I'm working with @liuliu and will complete before the end of this summer. I expect to make progress very fast, now that I've rewritten using more productive GPU and (soon) CPU-side test code.

**Comment by philipturner** [comment]
> Also, maybe do you want to extend this project in making a high level framework like Triton for Metal?

I want to integrate my research into Modular's Mojo, so we can escape the world where you must be a specialized expert to use AI software. We need to move on, to another era where AI is just another form of programming.

**Comment by brappier** [comment]
Thats great! 
You should keep logging your progress. Maybe just make a separate branch where you push stuff you try ( even stuff with bugs etc). 
We all can learn from you.

**Comment by philipturner** [comment]
> Also, folks from Apple are looking at your project closely!! Amazing work!

If anyone from Apple is watching, I have a major request. Please fix the sequential throughput bottleneck in MPSGraph. 58 microseconds for even the smallest operation is not acceptable. We need more control over how commands are encoded, which might be the biggest benefit of an open-source alternative.

https://gist.github.com/philipturner/d408351d68b5b1701bb651d4542e26e6/revisions#diff-7daadf283403c23e4b40fe4498187aea6a084a6eb23887425734445def1cb06cR1305

**Comment by philipturner** [comment]
Also, if there is a way to contact Apple, please fix Metal Frame Capture. It is unusable in most situations because it simply crashes when I try to run profiling. It is so severe that I spent 5 full days generating a simulation of (what would be) a frame capture, just to get insightful data.

https://gist.github.com/philipturner/d408351d68b5b1701bb651d4542e26e6

In another situation, I had to use [ui.perfetto.dev](https://ui.perfetto.dev) because Metal Frame Capture also crashes when you capture commands issued by the OpenCL driver. I am planning to migrate [openmm-metal](https://github.com/philipturner/openmm-metal) to the Metal API directly, solely to bypass a driver latency bottleneck. So OpenCL might not be a priority.

Finally, please this fix this bug in the OpenCL driver: https://github.com/philipturner/openmm-metal/blob/75048687ac9f11a3e0565d7df5e7b658215644ce/platforms/metal/src/MetalContext.cpp#L889. There was an entire research paper published with results saying M1 Ultra was faster than A100, because of this bug.

**Comment by philipturner** [comment]
> Also, folks from Apple are looking at your project closely!!

How did you learn about this? Do you have a contact at Apple? I'm waiting confirmation on the %FLOPS in SDXL that come from convolutions. There might be a way they can improve MPSGraph 3x3 convolutions while I focus my remaining time on just FlashAttention.

**Comment by philipturner** [comment]
I can't verify that you actually have a contact at Apple, and you have been saying similar things on Liu's repository, so I will close this issue.
