### ISSUE TITLE
Compute Command Encoder Question

### ISSUE THREAD

**Issue by jafioti** [philipturner/metal-flash-attention#18]
In the documentation it says "Batch 8 or more compute commands into the same MTLComputeCommandEncoder."

How is this done? I was under the impression that individual kernels were encoded in single command encoders using `set_compute_pipeline_state` and the inputs / outputs were set that way, and then many command encoders were created on the same buffer. Is it possible to do multiple kernels per command encoder, and is there a benifit over one kernel per command encoder, many command encoders per command buffer?

**Comment by philipturner** [comment]
There is immense overhead to encode kernels on the CPU in separate encoders or command buffers. This latency (~10 microseconds) is non-trivial and messes with profiling.

I typically profile matrix multiplies by encoding the exact same command 20 times in the same encoder (set the pipeline once, call dispatchThreads 20 times). Then, launch a command buffer with a single encoder in it. Then, stall on the CPU until the command buffer completes. Query the command buffer’s execution time. Repeat this process 15 times. So effectively 300 samples are taken.

The number 20 per command buffer served to amortize the high latency of work that doesn’t fully utilize the parallelism of the GPU (e.g. very small matrices that are still important to optimize). I divide the time of the entire buffer by 20, because this finds the back-to-back command execution time when no other latency bottlenecks are present.
